FROM ubuntu:latest
WORKDIR /home
RUN apt update
RUN apt --assume-yes install openjdk-11-jdk curl
RUN mkdir -p downloads
RUN cd downloads
RUN mkdir -p confluencehome
RUN curl -L http://www.atlassian.com/software/confluence/downloads/binary/atlassian-confluence-8.5.7.tar.gz --output atlassian-confluence-8.5.7.tar.gz
RUN tar -xvf atlassian-confluence-8.5.7.tar.gz
ENV CONFLUENCE_HOME=/home/downloads/confluencehome
CMD ["atlassian-confluence-8.5.7/bin/start-confluence.sh", "-fg"]