version: "3"
name: jiracon

services:
  jira:
    depends_on:
      - postgresql
    image: jira-software-arm64:9.13.1
    networks:
      - atlassiannet
    volumes:
      - jiradata:/var/atlassian/jira
    ports:
      - "8080:8080"
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

  confluence:
    depends_on:
      - postgresql
    image: confluence-server-arm64:8.5.7
    networks:
      - atlassiannet
    volumes:
      - confluencedata:/var/atlassian/confluence
    environment:
      - "CONFLUENCE_HOME=/home/downloads/confluencehome"
    ports:
      - "8090:8090"
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

  postgresql:
    image: postgres:9.5-alpine
    networks:
      - atlassiannet
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    environment:
      # Database hostname is `postgresql` inside Jira
      - "POSTGRES_USER=jira"
      # CHANGE THE PASSWORD!
      - "POSTGRES_PASSWORD=Postgres_password"
      - "POSTGRES_DB=jiradb"
      - "POSTGRES_ENCODING=UNICODE"
      - "POSTGRES_COLLATE=C"
      - "POSTGRES_COLLATE_TYPE=C"
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

volumes:
  jiradata:
    external: false
  confluencedata:
    external: false
  postgresqldata:
    external: false

networks:
  atlassiannet:
    driver: bridge
